# for test purpose
# you need combine them to produce env manually

# docker run -itd -p 2510:2510 -v /Users/terrill/temp:/usr/local/bin/data dcc:v0.0.1 serve
# docker run -itd -v /Users/terrill/temp:/usr/local/bin/data dcc-test:v0.0.1

version: "2"
services:
  # dcc is for sidecar reduction
  dcc:
    image: dcc:v0.0.1
    ports:
      - "2510:2510"
    volumes:
      # it's important for container to mount the same value
      - /Users/terrill/temp:/usr/local/bin/data
    entrypoint: dcc serve
  # dcc-test is for app inside which a dcc.sh contained
  dcc-test:
    image: dcc-test:v0.0.1
    volumes:
      - /Users/terrill/temp:/usr/local/bin/data